// Internal / Debug Use
export const REDUX_EVENT = '@@__REDUX_EVENT';
export const SET_LOGLEVEL = '@@__REDUX_EVENT__SET_LOGLEVEL';

// External Use
export const DISPATCH_EVENT = '@@__REDUX_EVENT__DISPATCH_EVENT';
export const ADD_EVENT_LISTENER = '@@__REDUX_EVENT__ADD_EVENT_LISTENER';
export const REMOVE_EVENT_LISTENER = '@@__REDUX_EVENT__REMOVE_EVENT_LISTENER';
export const REMOVE_ALL_LISTENERS_FOR_EVENT = '@@__REDUX_EVENT__REMOVE_ALL_LISTENERS_FOR_EVENT';
export const REMOVE_ALL_LISTENERS_FOR_CONTEXT = '@@__REDUX_EVENT__REMOVE_ALL_LISTENERS_FOR_CONTEXT';
